# LAB 01.01 - Practice submission

In [3]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/fagonzalezo/ai4eng-unal/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()


In [4]:
import inspect
from local.lib.rlxmoocapi import session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="student");

logging in as otoledo@unal.edu.co ... please wait
using course session ai4eng.v1.unal::intro_si_2025_1
success!! you are logged in


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [5]:

def suma_matrices(a,b):
    ## --- TU CODIGO AQUI ---
    result = a + b
    return result



comprueba manualmente tu código

In [6]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (suma_matrices(a,b))

[[6 9]
 [7 6]
 [1 3]]
[[9 1]
 [9 6]
 [0 4]]
[[15 10]
 [16 12]
 [ 1  7]]


#### registra tu solución en línea

In [7]:
student.submit_task(globals(), task_id="task_01");

### Ejercicio 2: Realiza un cálculo

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [8]:
import numpy as np
rlist = np.random.randint(100, size=10)
rlist

array([86, 24, 39, 48, 58, 63, 89,  0, 75, 62])

#### tu solución

In [9]:
avg = rlist.mean()
print(avg)

54.4


#### registra tu solución en línea

In [10]:
student.submit_task(globals(), task_id="task_02");