# LAB 01.01 - Practice submission

In [1]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/fagonzalezo/ai4eng-unal/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()


replicating local resources


In [ ]:
import inspect
from local.lib.rlxmoocapi import session # type: ignore
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="student");

### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [3]:

def suma_matrices(a,b):
    ## --- TU CODIGO AQUI ---
    result = a + b
    return result



comprueba manualmente tu código

In [4]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (suma_matrices(a,b))

[[1 3]
 [9 0]
 [0 7]]
[[0 4]
 [3 8]
 [6 9]]
[[ 1  7]
 [12  8]
 [ 6 16]]


#### registra tu solución en línea

In [5]:
student.submit_task(globals(), task_id="task_01");

### Ejercicio 2: Realiza un cálculo 

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [6]:
import numpy as np
rlist = np.random.randint(100, size=10)
rlist

array([29, 78, 22, 23, 46, 16, 14, 28, 80, 41])

#### tu solución

In [7]:
avg = rlist.mean()
print(avg)

37.7


#### registra tu solución en línea

In [8]:
student.submit_task(globals(), task_id="task_02");